### ISSUE TITLE
Adding some softwares to your list

### ISSUE THREAD

**Issue by Gracrys** [LisaDziuba/Awesome-Design-Tools#113]
For pixel art, i use rn Aseprite but highly recommend grafx2, which is a old software but really great, and some i used before, which is graphicsgale

also for the icons part, i use flaticon

i think adding what is recommended over the other options may also help, but that is up to you

**Comment by LisaDziuba** [comment]
@Gracrys, sorry for such a late reply! Thanks for your recommendations :) We'll add those tools today!
