### ISSUE TITLE
Consider adding a "Learn Design" Category

### ISSUE THREAD

**Issue by ericalli** [LisaDziuba/Awesome-Design-Tools#131]
There are some great online courses available to learn UI/UX design. A new category for these would be great. A few to start with could include:

- [Learn UI Design](https://learnui.design)
- [Design Better](https://www.designbetter.co)
- [DesignerUp](https://designerup.co)
- [Sketch Master](https://sketchmaster.com)
- [Learn UX](https://learnux.io)
- [Laws of UX](https://lawsofux.com)
- [Design+Code](https://designcode.io)

**Comment by LisaDziuba** [comment]
wow! that's a great idea! @valianka what do you think?

**Comment by valianka** [comment]
@ericalli & @LisaDziuba awesome, let's make a new section :)

**Comment by LisaDziuba** [comment]
Now we have a new category 🎉
Please add good learning resources here: [Tools for Learning Design](https://github.com/LisaDziuba/Awesome-Design-Tools/blob/master/README.md#tools-for-learning-design)
