### ISSUE TITLE
Be able to filter the tools tags

### ISSUE THREAD

**Issue by evalica** [LisaDziuba/Awesome-Design-Tools#154]
Great project and work - thanks for contributing all of this!

I would love to have a way to filter the tools listed. The categories are great and I really appreciate the tags, but I would want to filter them. For example, 
* I would want to know what Open Source tool there is for Accessibility Tools. 
* What Mac compatible tools are there?
* Which tools are web based? 

I would imagine some filters (select) at the top of the tools list that I could tweak and find my answer faster than browsing or using the browser's search functionality.

Wdyt?

**Comment by berezovskycom** [comment]
Hi @evalica! Thanks for your feedback!
Yes, filtering will be a great feature for the next release.
Plus we already have it on Awesome Design Plugins.
Currently we have only 3 categories: mac, free and open source.
Mapping through all Tools, searching for web based ones might take some time, feel free to contribute! We already have an icon for Web Tools.
Great idea on filtering! Thanks!

**Comment by LisaDziuba** [comment]
I'm keeping this issue open for now.

**Comment by LisaDziuba** [comment]
Checked with the team - we already made this 👌
