### ISSUE TITLE
Development tools category?

### ISSUE THREAD

**Issue by wouterlanduydt** [LisaDziuba/Awesome-Design-Tools#199]
Hi @LisaDziuba,

I think a section of development tools would suit this list.

As designers & developers often work closely together to work on UI, I guess this would make sense. Think tools like Storybook and Styleguidist.

- [Storybook](https://storybook.js.org/) - An open source tool for developing UI components in isolation for React, Vue, and Angular. It makes building stunning UIs organized and efficient.
- [Styleguidist](https://react-styleguidist.js.org/) - Isolated React component development environment with a living style guide.
- ...

Thoughts on this?

**Comment by LisaDziuba** [comment]
Oh, somehow I missed this issue! So sorry! 

I merged Development Browsers wit your suggested development tools :) So now we have the Development Tools category!
