### ISSUE TITLE
Legends

### ISSUE THREAD

**Issue by toseefkhilji** [LisaDziuba/Awesome-Design-Tools#2]
It would be great if there is some legends.
like this: 
![screenshot 2019-02-14 at 6 01 41 pm](https://user-images.githubusercontent.com/2367614/52787051-b7db6000-3082-11e9-9e1d-67f5e02688ba.png)
Example.
![screenshot 2019-02-14 at 6 02 10 pm](https://user-images.githubusercontent.com/2367614/52787089-cc1f5d00-3082-11e9-9764-b2bc3626906b.png)

**Comment by LisaDziuba** [comment]
@toseefkhilji totally makes sense! We'll do with @valianka this week.
Thanks a lot!!!

**Comment by LisaDziuba** [comment]
hey, @toseefkhilji!
What do you think about such legend?

![image](https://user-images.githubusercontent.com/23191656/53290482-fb357d00-37ac-11e9-98f6-0dc3aa874564.png)

**Comment by d2s** [comment]
@LisaDziuba Apple icon might work a bit better with a transparent background colour.

**Comment by toseefkhilji** [comment]
@LisaDziuba Great!!!

**Comment by LisaDziuba** [comment]
@toseefkhilji great! we added it to the Contribution Guidelines and now I will add labels to the into part in Readme file. So people will see that it's important to add labels with their submissions.

As there are 150+ tools over the repo, it might take some time to review all tools and add labels. We'll start doing it with @valianka. I'm happy to see that our list becomes more and more awesome thanks to you, guys!

@d2s - Valia changed Apple icon 🍏

**Comment by LisaDziuba** [comment]
I'm closing the issue as we have legend and only need to implement it :)
