### ISSUE TITLE
Behance Free Fonts link is broken.

### ISSUE THREAD

**Issue by kimpetersend1** [LisaDziuba/Awesome-Design-Tools#208]
<img width="1190" alt="Screen Shot 2019-06-06 at 14 27 09" src="https://user-images.githubusercontent.com/8875499/59032712-3729b500-8867-11e9-80f6-f1276c432308.png">

**Comment by kelvinelove** [comment]
I noticed that too. The correct link should be https://www.behance.net/search/?search=free%20font
