### ISSUE TITLE
Labels not shown in Firefox

### ISSUE THREAD

**Issue by inliquid** [LisaDziuba/Awesome-Design-Tools#227]
When viewing README in FF, there are no icons at all, just a free space:
![изображение](https://user-images.githubusercontent.com/6797881/62971506-b1078d00-be1a-11e9-959f-6bb6588ae776.png)

![изображение](https://user-images.githubusercontent.com/6797881/62971431-887f9300-be1a-11e9-9f70-ebf9727d6fbf.png)

**Comment by berezovskycom** [comment]
Hi @inliquid! Thanks for noticing!
I'm sorry for your bug, has it been fixed?
If not, could you please specify your Firefox Browser version?
Thanks!

**Comment by LisaDziuba** [comment]
hey @inliquid!
I hope, the issue has been resolved, so I'm closing it.

**Comment by inliquid** [comment]
It works! Thank you.
