### ISSUE TITLE
Telegram Channel 

### ISSUE THREAD

**Issue by ribadima** [LisaDziuba/Awesome-Design-Tools#26]
You can create a Telegram Channel where the repository updates will be periodically added (about tools).

**Comment by LisaDziuba** [comment]
@ribadima, thanks for suggestion, I need to research more.
As Telegram is very popular in Ru-speaking countries. Not sure if it's that spread between English-speaking community.

In general idea is very good.

@valianka, what do you think?

**Comment by ribadima** [comment]
Optimal channel for the distribution of updates will be a twitter account or regular email with the subscription. About Telegram - it has a relatively small audience in the world but is common among IT professionals

**Comment by LisaDziuba** [comment]
I will close this issue for now, as we're not sure about Telegram channel or another distribution channel.
