### ISSUE TITLE
Adding blocksapp

### ISSUE THREAD

**Issue by WhiteLeash** [LisaDziuba/Awesome-Design-Tools#29]
Hey! I don't have even now time to pull request (watching this repo through phone) but it would be nice if on list would be https://blocsapp.com/ for building web app/prototyping app.
Cheers

**Comment by LisaDziuba** [comment]
@WhiteLeash thanks! we have a section for that.
I'll add today.

**Comment by LisaDziuba** [comment]
Added ✔
