### ISSUE TITLE
Categorize by free/paid?

### ISSUE THREAD

**Issue by aolko** [LisaDziuba/Awesome-Design-Tools#31]
Please tag the tools with free or paid, people gotta know what they are getting into.

**Comment by LisaDziuba** [comment]
@aolko 💯!
We'll make a legend soon.

**Comment by LisaDziuba** [comment]
hey @aolko what do you think about such legend?

![image](https://user-images.githubusercontent.com/23191656/53290505-57000600-37ad-11e9-9a6d-c57c3d118d65.png)

**Comment by LisaDziuba** [comment]
some update:

we added free tool label to the Contribution Guidelines and now I will add labels to the into part in Readme file. So people will see that it's important to add labels with their submissions.

As there are 150+ tools over the repo, it might take some time to review all tools and add labels. We'll start doing it with @valianka. 

As free\paid labels exist already, I'm closing the issue.

**Comment by aolko** [comment]
Existing tools are not entirely categorized, please fix
