### ISSUE TITLE
Information architecture and testing tools?

### ISSUE THREAD

**Issue by rubymorillo** [LisaDziuba/Awesome-Design-Tools#58]
Hi @LisaDziuba!

How do you feel about including a category for information architecture and testing tools? I was thinking Optimal Workshop's suite of tools might be a good fit here. Example for information architecture:

* [OptimalSort](https://www.optimalworkshop.com/optimalsort) — card sorting tool that allows you to understand how people categorize content in your UI
* [Treejack](https://www.optimalworkshop.com/treejack) — upload your proposed sitemap to see how a user would move through your site

Any thoughts?

**Comment by LisaDziuba** [comment]
@rubymorillo I'm so sorry for such a late reply to this issue! We got a lot of tasks for repo (especially to add free\paid labels for 250 tools 🤦‍♀️)

I agree on adding the tools which help with testing UI hypothesis. However, I'm not sure if 
information architecture is the most understandable title for the section. I saw its on the tools' websites but it should be understandable to the design & tech community in the first place.

Let's do it like you proposed for now and check in a week or two if someone will submit more tool there. Thanks again for contributions ❤
