### ISSUE TITLE
Inkscape

### ISSUE THREAD

**Issue by perfecto25** [LisaDziuba/Awesome-Design-Tools#66]
great list!

can you add Inkscape as a UI Design tool, its open src vector software similar to Illustrator

https://inkscape.org/

**Comment by LisaDziuba** [comment]
hey, @perfecto25! Thanks for recommending the tool. You can simply send PRs according to these [guidelines](https://github.com/LisaDziuba/Awesome-Design-Tools/blob/master/Contribution_Guidelines.md)

I appreciate your collaboration.
