### ISSUE TITLE
Please, help us to mention similar tools for every category

### ISSUE THREAD

**Issue by LisaDziuba** [LisaDziuba/Awesome-Design-Tools#84]
It's possible to do similar tasks with tools in different categories. Many design tools are multidisciplinary (you can do prototypes, UX & UI, logos in Sketch). However, it doesn't make sense to put the same tools several times.

**It will be very nice to write one-two sentences at end of categories about tools that can be used for the same task.**

So if someone have a desire to share expert opinion on similar tools, I & @valianka will be super happy for such help 🙏

**How to help**: write sentences mentioning similar tools from different categories (when you think it's appropriate). Send Pull Requests. 

Examples:
<details>

![image](https://user-images.githubusercontent.com/23191656/53664679-de4bee80-3c71-11e9-906f-4466b4a7dbc8.png)

![image](https://user-images.githubusercontent.com/23191656/53664799-47cbfd00-3c72-11e9-83b8-ab1d665520c1.png)

**Comment by mohamedanees6** [comment]
@LisaDziuba Can I work on this?

**Comment by LisaDziuba** [comment]
@mohamedanees6 
**sure! It will be great if you help us with this issue.**

The easiest way to start is to look 14 tools in the [UI Design Tools](https://github.com/LisaDziuba/Awesome-Design-Tools/blob/master/README.md#ui-design-tools) section. When you open their websites, you probably will find if it's possible to do another tasks in those tools (like animation, prototyping, illustrations, logo design, user flows, etc). 

I have a feeling that many tools from UI Design Tools section are multidisciplinary, so can be mentioned in another category.

When you have some thoughts 🤔 on tools to mention in another categories, just make PR to Readme file. I or @valianka will merge it asap.

Please, let me know if anything needed from our side.
Thank you again!

**Comment by mohamedanees6** [comment]
#89 Added some common logo creation tools

**Comment by LisaDziuba** [comment]
@mohamedanees6 I think, thanks to your help we added all needed tools in different categories. I'm sending you a lot of hugs and thanks 💕 And successfully closing this issue.
