### ISSUE TITLE
Should we create Screen-Recording Tools category?

### ISSUE THREAD

**Issue by LisaDziuba** [LisaDziuba/Awesome-Design-Tools#85]
Some designer on Reddit suggested to add tools, which allow to record the screen. 
Do you think we need such category? Are there enough tools? 

I feel it's very close to [Free Screenshot Software](https://github.com/LisaDziuba/Awesome-Design-Tools#free-screenshot-software) category.

@valianka 💕, @ribadima 🎨, @kevin-miles 💻, @rubymorillo <img src="https://user-images.githubusercontent.com/23191656/53687438-4ddae000-3d3d-11e9-9bbf-ce7dd7a03699.png" width="15" height="15"> what do you think?

**Comment by JorgeCruces** [comment]
Yes, please!
