### ISSUE TITLE
Consider adding a `Browser Extensions` category

### ISSUE THREAD

**Issue by randydaniel** [LisaDziuba/Awesome-Design-Tools#92]
There are some great Chrome/Firefox extensions that aid the design & development process. Perhaps we can have a `Browser Extensions` category?

**Comment by LisaDziuba** [comment]
hey, @randydaniel! sorry for being soooo slow!
I think that many design tools have some Browser Extensions. Do you have a few in mind?

**Comment by marceloavf** [comment]
Hey @LisaDziuba, there is some extensions that I use here, hope it helps.

- [Muzli](https://chrome.google.com/webstore/detail/muzli-2-stay-inspired/glcipcfhmopcgidicgdociohdoicpdfc?hl=pt-BR) - Stay inspired at every new tab.
- [Panda](https://usepanda.com/) - Same as above.
- [Awesome Screenshot](https://chrome.google.com/webstore/detail/awesome-screenshot-screen/nlipoenfbbikpbjkfpfillcgkoblgpmj) - Record video or take picture of the web page.
- [Axe](https://chrome.google.com/webstore/detail/axe/lhdoppojpmngadmnindnejefpokejbdd) - Accessibility test tools.
- [Browser Calories](https://chrome.google.com/webstore/detail/browser-calories/pdkibgfjegigkoaleelbkdpkgceljfco) - Test performance budget of your application.
- [CSS Peeper](https://chrome.google.com/webstore/detail/css-peeper/mbnbehikldjhnfehhnaidhjhoofhpehk) - Extract CSS and build beautiful styleguides.
- [Noisli](https://chrome.google.com/webstore/detail/noisli/klejemegaoblahjdpcajmpcnjjmkmkkf) - Improve your focus and boost your productivity. Block out annoying noises and create the right environment for working or relaxing.
- [Page Ruler](https://chrome.google.com/webstore/detail/page-ruler/emliamioobfffbgcfdchabfibonehkme) - Page Ruler lets your draw out a ruler to any page and displays the width, height and position of it.
- [Palettab](https://chrome.google.com/webstore/detail/palettab/bidckpnndigbjhmojikkhmejkfkpgoih) - Bringing awesome colors and fonts to the new tab page! A little bit of something fresh every time you hit that new tab button.
- [Session Buddy](https://chrome.google.com/webstore/detail/session-buddy/edacconmaakjimmfgnblocblbcdcpbko) - Manage Browser Tabs and Bookmarks with Ease.
- [Visual Inspector](https://chrome.google.com/webstore/detail/visual-inspector-by-canva/efaejpgmekdkcngpbghnpcmbpbngoclc) - Collaboration tool for website feedback and fixing design bugs.

**Comment by randydaniel** [comment]
Having a category dedicated to browser extensions is not required.
